<?php

/**
* Model base class generated by the Wave\DB ORM.
* Changes made to this file WILL BE OVERWRITTEN when database is next parsed.
* To add/override functionality, edit the child stub class.
*
* @package:   Wave\DB
* @generated: <<current_timestamp>>
*
* @schema:    <<table_schema>>
* @table:     <<table_name>>
* @engine:    <<table_engine>>
* @collation: <<table_collation>>
*
*/

namespace <<namespace>>\Base;
use \Wave\DB;

abstract class <<class_name>> extends <<base_model>> {

	//Table name
	protected static $_schema_name = '<<database_namespace>>';
	protected static $_table_name = '<<table_name>>';
	
	//Columns
	protected static $_fields = array(