<?php

/**
* Stub model generated by the Wave_DB ORM.
* Changes made to this file will not be overwritten.
*
* @package:   Wave_DB
* @generated: <<current_timestamp>>
*
* @schema:    <<table_schema>>
* @table:     <<table_name>>
* @engine:    <<table_engine>>
* @collation: <<table_collation>>
*
*/

class <<class_name>> extends <<base_class_name>> {



}

?>